version: '3.1' # 컴포즈 사용 버전

services:      # 아래에 내가 사용할 컨테이너 기술
  mysql:
    image: mysql:8                # 내가 사용할 이미지
    container_name: mysql-dev   # 내가 로드할 컨테이너 이름
    environment:                  # 위에 env파일에 해당하는 환경변수
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:                      # 위 이미지랑 연결되는 포트
      - ${MYSQL_HOST_PORT}:${MYSQL_DOCKER_PORT}
    volumes:                    # 영속성을 위한 데이터 저장 경로
      - mysql_data:/var/lib/mysql
    restart: always

  redis:
    image: redis
    container_name: redis-dev
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_DOCKER_PORT}
    volumes:
      - redis_data:/var/lib/redis
    restart: always

volumes:
  redis_data:
  mysql_data:
