version: '3'
services:
  proxy:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: rkwhr00725@gmail.com
      # variable names are space-separated
      ENVSUBST_VARS: FQDN
      FQDN: seokhoserver.site
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
  nestjs:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
volumes:
  letsencrypt:
