version: '3'

services:
  nestjs:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
