name: CI/CD Docker

on:
  push:
    branches: [main]

jobs:
  build:
    name: run
    runs-on: [ self-hosted, Linux, x64 ]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set remote and pull
        run: |
          git pull origin main

      - name: Stop Docker Compose
        run: |
          sudo docker-compose down

      - name: Delete nestjs image
        run: |
          IMAGE_NAME="server-eric-nestjs"
          if sudo docker images --quiet ${IMAGE_NAME}; then
          sudo docker rmi -f ${IMAGE_NAME}
          fi
      - name: Restart Docker Compose
        run: |
          sudo docker-compose up -d