name: CI/CD Docker

on:
  push:
    branches: [main]

jobs:
  build:
    name: run
    runs-on: [ self-hosted, Linux, x64 ]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set remote and pull
        run: |
          git pull origin main

      - name: Stop Docker Compose
        run: |
          sudo docker-compose down

      - name: Remove Docker image if exists
        run: |
          IMAGE_NAME="server-eric_nestjs"
          # 이미지 이름에 "server-eric_nestjs"가 포함된 이미지를 찾아서 삭제
          if sudo docker images --quiet --filter "reference=${IMAGE_NAME}*" | grep . ; then
            sudo docker images --quiet --filter "reference=${IMAGE_NAME}*" | xargs sudo docker rmi -f
          fi

      - name: Restart Docker Compose
        run: |
          sudo docker-compose up -d