name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo apt-get install -y docker-compose

      - name: Remove containerd.io
        run: |
          sudo apt-get remove containerd.io
        if: success()

      - name: Build and Push Docker Images
        run: |
          cd app
          docker build -t your-nest-app-image .
          docker tag your-nest-app-image your-docker-hub-username/your-nest-app-image:latest
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push your-docker-hub-username/your-nest-app-image:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose up -d
