name: CI/CD Docker

on:
  push:
    branches: [main]

jobs:
  build:
    name: run
    runs-on: [ self-hosted, Linux, x64 ]
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set remote and pull
        run: |
          git pull origin main

      - name: Stop Docker Compose
        run: |
          sudo docker-compose down

      - name: Remove Docker image if exists
        run: |
          IMAGE_NAMES=("server-eric-nestjs" "nginx")
          # 각 이미지 이름에 대해 확인 후 이미지가 존재하면 삭제
          for IMAGE_NAME in "${IMAGE_NAMES[@]}"; do
          if sudo docker images --quiet --filter "reference=${IMAGE_NAME}*" | grep . ; then
          sudo docker images --quiet --filter "reference=${IMAGE_NAME}*" | xargs sudo docker rmi -f
          fi
          done

      - name: Restart Docker Compose
        run: |
          sudo docker-compose up -d